name: crypto_template
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  flutter_sparkline: ^0.1.0
  font_awesome_flutter: ^8.4.0
  shimmer: ^0.0.6
  rxdart: ^0.21.0
  bmnav: ^0.3.4
  carousel_slider: ^3.0.0
  percent_indicator: ^1.0.15
  shared_preferences: ^0.5.12+4
  form_field_validator: ^1.0.1
  http: ^0.12.2
  flushbar: ^1.10.4
  get: ^3.22.2
  qr_flutter: ^3.1.0
  # get_mac: ^0.0.1
  webview_flutter: ^1.0.7
  crypto: ^2.1.5
  crypto_font_icons: ^0.1.0+1
  share: ^0.6.5+4
  connectivity: ^2.0.2
  k_chart: ^0.1.2
  intl: ^0.16.1
  web_socket_channel: ^1.2.0
  intl_phone_field: ^1.4.2
  oktoast: ^2.3.2
  image_picker: ^0.6.7+22
  introduction_screen: ^1.0.9
  upgrader: ^2.8.2
  firebase_messaging: ^7.0.3
  badges: ^1.1.6
  flutter_dotenv: ^3.1.0


dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  image_path: "assets/image/b4u_logo.png" 
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: gainers
      fonts:
        - asset: assets/icon/ic_gainers.ttf
    - family: message
      fonts:
        - asset: assets/icon/ic_message.ttf
    - family: tab
      fonts:
        - asset: assets/icon/ic_tab.ttf
    - family: wallet
      fonts:
        - asset: assets/icon/ic_wallet.ttf
    - family: tab1
      fonts:
        - asset: assets/icon/ic_tab1.ttf
    - family: tab2
      fonts:
        - asset: assets/icon/ic_tab2.ttf
    - family: tab3
      fonts:
        - asset: assets/icon/ic_tab3.ttf
    - family: tab4
      fonts:
        - asset: assets/icon/ic_tab4.ttf
    - family: tab5
      fonts:
        - asset: assets/icon/ic_tab5.ttf
    - family: loser
      fonts:
        - asset: assets/icon/ic_loser.ttf
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600
    - family : Pragmatica
      fonts:
        - asset: assets/font/pragmatica_bold.ttf
          weight: 500
    - family: CryptoFont
      fonts:
        - asset: assets/font/cryptofont-webfont.ttf
          weight: 500

  assets:
    - assets/ilustration/b1.png
    - assets/ilustration/b2.png
    - assets/ilustration/b3.png
    - assets/ilustration/noData.png
    - assets/image/banner/banner1.png
    - assets/image/banner/banner2.png
    - assets/image/banner/banner3.jpg
    - assets/image/banner/banner4.png
    - assets/image/b4u_logo.png
    - assets/image/b4u_wallet_logo.png
    - assets/image/gainers.png
    - assets/image/losers.png
    - assets/image/News_Image/Asia.jpg
    - assets/image/News_Image/BlockStream.jpg
    - assets/image/News_Image/BNB.jpg
    - assets/image/News_Image/CBOE.jpg
    - assets/image/News_Image/CryptoBroker.jpg
    - assets/image/News_Image/EOSget.jpg
    - assets/image/News_Image/MarketSentiment.jpg
    - assets/image/News_Image/Mt.Gox.jpg
    - assets/image/News_Image/NewCripto.jpg
    - assets/image/News_Image/Twitter.jpg
    - assets/image/News_Image/YouCan.jpg
    - assets/image/News_Image/Ziliqa.jpg
    - assets/image/google_authenticator.png
    - assets/depth.json
    - assets/graph_type.json
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
